/* ═══════════════════════════════════════════════════════════
   curriculum.js  —  Java Backend Roadmap Content Data
   ═══════════════════════════════════════════════════════════ */

const PHASES = [
  {
    id: "phase-1",
    num: "Faza 1",
    icon: "☕",
    name: "Java Temelleri",
    desc: "Java dilini sıfırdan öyrən, OOP prinsiplərini mənimsə",
    color: "#22c55e",
    sections: ["getting-started", "java-fundamentals", "oop"],
    topics: 21,
    hours: 40,
  },
  {
    id: "phase-2",
    num: "Faza 2",
    icon: "⚡",
    name: "Advanced Java",
    desc: "Generics, Streams, Concurrency, dizayn prinsipləri",
    color: "#3b82f6",
    sections: [
      "advanced-java",
      "concurrency",
      "jvm-internals",
      "design-patterns",
    ],
    topics: 30,
    hours: 66,
  },
  {
    id: "phase-3",
    num: "Faza 3",
    icon: "🔧",
    name: "Build & Database",
    desc: "Maven, Gradle, SQL, JDBC, connection pooling",
    color: "#a855f7",
    sections: ["build-tools", "databases"],
    topics: 13,
    hours: 26,
  },
  {
    id: "phase-4",
    num: "Faza 4",
    icon: "🌱",
    name: "Spring Ekosistemi",
    desc: "Spring Core, Spring Boot, REST API, JPA, Hibernate",
    color: "#f89820",
    sections: [
      "spring-core",
      "spring-boot",
      "rest-apis",
      "reactive",
      "jpa-hibernate",
    ],
    topics: 40,
    hours: 78,
  },
  {
    id: "phase-5",
    num: "Faza 5",
    icon: "🔐",
    name: "Security & Testing",
    desc: "Spring Security, JWT, OAuth, JUnit, Mockito, TDD",
    color: "#ef4444",
    sections: ["spring-security", "testing"],
    topics: 16,
    hours: 30,
  },
  {
    id: "phase-6",
    num: "Faza 6",
    icon: "🐳",
    name: "Infrastructure",
    desc: "Redis, Kafka, RabbitMQ, Docker, Container Orchestration",
    color: "#14b8a6",
    sections: ["caching", "messaging", "docker"],
    topics: 17,
    hours: 32,
  },
  {
    id: "phase-7",
    num: "Faza 7",
    icon: "☸️",
    name: "Architecture & Ops",
    desc: "Microservices, Monitoring, Cloud, DevOps, CI/CD",
    color: "#6366f1",
    sections: ["microservices", "monitoring", "cloud-devops"],
    topics: 18,
    hours: 38,
  },
  {
    id: "phase-8",
    num: "Faza 8",
    icon: "🎯",
    name: "Career & Interview",
    desc: "İş müsahibəsinə hazırlıq, sistem dizaynı, kodlama sualları",
    color: "#eab308",
    sections: ["interview-prep"],
    topics: 6,
    hours: 16,
  },
];

const CURRICULUM = [
  /* ─────────────────────────────────────────
     SECTION 01 — Getting Started
     ───────────────────────────────────────── */
  {
    id: "getting-started",
    num: "01",
    icon: "🚀",
    title: "Getting Started",
    level: "Başlanğıc",
    color: "#22c55e",
    bg: "linear-gradient(135deg,#14532d,#166534)",
    hours: 8,
    desc: "Java Backend development dünyasına ilk addım. Mühit quraşdırma, JVM arxitekturası və ilk proqram.",
    topics: [
      {
        id: "gs-1",
        title: "Java Backend nədir?",
        mins: 30,
        tags: ["theory"],
        subtopics: [
          "Backend vs Frontend",
          "Java-nın üstünlükləri",
          "Böyük şirkətlərdə Java",
          "Career paths",
          "Roadmap haqqında",
        ],
      },
      {
        id: "gs-2",
        title: "JDK, JRE, JVM – fərqlər",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "JVM nədir?",
          "JRE nədir?",
          "JDK nədir?",
          "Bytecode necə işləyir?",
          "Platform müstəqilliyi",
        ],
      },
      {
        id: "gs-3",
        title: "IDE & Development Mühiti",
        mins: 45,
        tags: ["setup", "practice"],
        subtopics: [
          "IntelliJ IDEA quraşdırma",
          "JDK 17+ quraşdırma",
          "İlk layihə yaratmaq",
          "IDE shortcuts",
          "Maven ilk addım",
        ],
      },
      {
        id: "gs-4",
        title: "İlk Java Proqramı",
        mins: 35,
        tags: ["practice"],
        subtopics: [
          "Hello World",
          "main() metodu",
          "javac və java komandaları",
          "Proqramın icrası",
          "Ümumi xətalar",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 02 — Java Fundamentals
     ───────────────────────────────────────── */
  {
    id: "java-fundamentals",
    num: "02",
    icon: "☕",
    title: "Java Fundamentals",
    level: "Başlanğıc",
    color: "#3b82f6",
    bg: "linear-gradient(135deg,#1e3a5f,#1d4ed8)",
    hours: 22,
    desc: "Dəyişənlər, data tiplər, operatorlar, idarəetmə strukturları, massivlər, stringlər və metodlar.",
    topics: [
      {
        id: "jf-1",
        title: "Variables & Data Types",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Primitive types (int, long, double, boolean…)",
          "Reference types",
          "Type casting",
          "var keyword (Java 10+)",
          "Dəyişən adlandırma qaydaları",
        ],
      },
      {
        id: "jf-2",
        title: "Operators & Expressions",
        mins: 45,
        tags: ["theory", "practice"],
        subtopics: [
          "Arithmetic operators",
          "Comparison operators",
          "Logical operators",
          "Bitwise operators",
          "Ternary operator",
          "Operator precedence",
        ],
      },
      {
        id: "jf-3",
        title: "Control Flow – if/else & switch",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "if / else if / else",
          "Nested conditions",
          "switch statement",
          "switch expression (Java 14+)",
          "Pattern matching (Java 17+)",
        ],
      },
      {
        id: "jf-4",
        title: "Loops – for, while, do-while",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "for loop",
          "enhanced for-each",
          "while loop",
          "do-while loop",
          "break & continue",
          "Nested loops",
          "Loop performansı",
        ],
      },
      {
        id: "jf-5",
        title: "Arrays",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Array yaratmaq",
          "1D və 2D arrays",
          "Arrays sinfi (sort, fill, copyOf)",
          "Array üzərindən iteration",
          "Common array problems",
        ],
      },
      {
        id: "jf-6",
        title: "Strings & String Methods",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "String pool",
          "String metodları (length, substring, contains…)",
          "StringBuilder vs StringBuffer",
          "String.format()",
          "Text Blocks (Java 13+)",
          "Regular Expressions",
        ],
      },
      {
        id: "jf-7",
        title: "Methods & Recursion",
        mins: 90,
        tags: ["practice"],
        subtopics: [
          "Metod sintaksisi",
          "Return types",
          "Method overloading",
          "varargs",
          "Recursion anlayışı",
          "Recursion vs Iteration",
          "Rekursion misallar (Fibonacci, Factorial)",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 03 — OOP
     ───────────────────────────────────────── */
  {
    id: "oop",
    num: "03",
    icon: "🏛️",
    title: "Object-Oriented Programming",
    level: "Başlanğıc",
    color: "#f97316",
    bg: "linear-gradient(135deg,#431407,#ea580c)",
    hours: 28,
    desc: "4 OOP prinsipi (Encapsulation, Inheritance, Polymorphism, Abstraction) dərindən öyrən.",
    topics: [
      {
        id: "oop-1",
        title: "Classes & Objects",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Class anlayışı",
          "Object yaratmaq (new)",
          "Instance variables vs local variables",
          "toString(), equals(), hashCode()",
        ],
      },
      {
        id: "oop-2",
        title: "Constructors & this keyword",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "Default constructor",
          "Parametrli constructor",
          "Constructor overloading",
          "this keyword",
          "Constructor chaining",
        ],
      },
      {
        id: "oop-3",
        title: "Encapsulation & Access Modifiers",
        mins: 50,
        tags: ["theory", "practice"],
        subtopics: [
          "private, protected, public, default",
          "Getters & Setters",
          "Encapsulation niyə lazımdır?",
          "Record classes (Java 16+)",
        ],
      },
      {
        id: "oop-4",
        title: "Inheritance & super keyword",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "extends keyword",
          "super() çağırması",
          "Method overriding",
          "@Override annotation",
          "Object sinfi",
          "final keyword",
        ],
      },
      {
        id: "oop-5",
        title: "Polymorphism",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Compile-time polymorphism (overloading)",
          "Runtime polymorphism (overriding)",
          "Upcasting & Downcasting",
          "instanceof operator",
          "Pattern Matching (Java 16+)",
        ],
      },
      {
        id: "oop-6",
        title: "Abstract Classes",
        mins: 50,
        tags: ["theory", "practice"],
        subtopics: [
          "abstract class sintaksisi",
          "abstract metodlar",
          "Template Method pattern",
          "Abstract vs Concrete",
          "Nə zaman abstract class?",
        ],
      },
      {
        id: "oop-7",
        title: "Interfaces",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "interface sintaksisi",
          "Multiple interface implementation",
          "default metodlar (Java 8+)",
          "static metodlar",
          "functional interfaces",
          "Interface vs Abstract Class",
        ],
      },
      {
        id: "oop-8",
        title: "Static Members",
        mins: 40,
        tags: ["theory", "practice"],
        subtopics: [
          "static variables",
          "static metodlar",
          "static blocks",
          "Singleton pattern ilə əlaqə",
          "static vs instance",
        ],
      },
      {
        id: "oop-9",
        title: "Enums",
        mins: 35,
        tags: ["practice"],
        subtopics: [
          "Enum sintaksisi",
          "Enum metodları",
          "Enum-a field əlavə etmək",
          "Enum-u switch-də istifadə",
          "EnumSet, EnumMap",
        ],
      },
      {
        id: "oop-10",
        title: "Inner & Nested Classes",
        mins: 35,
        tags: ["theory"],
        subtopics: [
          "Static nested class",
          "Inner class",
          "Local class",
          "Anonymous class",
          "İstifadə nümunələri",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 04 — Advanced Java
     ───────────────────────────────────────── */
  {
    id: "advanced-java",
    num: "04",
    icon: "⚡",
    title: "Advanced Java",
    level: "Orta",
    color: "#eab308",
    bg: "linear-gradient(135deg,#422006,#d97706)",
    hours: 30,
    desc: "Exception handling, Collections, Generics, Lambda, Stream API, Optional, Date/Time API və File I/O.",
    topics: [
      {
        id: "aj-1",
        title: "Exception Handling",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "try-catch-finally",
          "Checked vs Unchecked exceptions",
          "Custom exceptions",
          "try-with-resources",
          "Multi-catch",
          "Exception hierarchy",
        ],
      },
      {
        id: "aj-2",
        title: "Collections Framework – List",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "ArrayList vs LinkedList",
          "List metodları",
          "List-i sort etmək",
          "ListIterator",
          "Collections utility sinfi",
        ],
      },
      {
        id: "aj-3",
        title: "Collections Framework – Set & Queue",
        mins: 50,
        tags: ["theory", "practice"],
        subtopics: [
          "HashSet, LinkedHashSet, TreeSet",
          "Set əməliyyatları",
          "Queue & Deque",
          "PriorityQueue",
          "ArrayDeque",
        ],
      },
      {
        id: "aj-4",
        title: "Collections Framework – Map",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "HashMap, LinkedHashMap, TreeMap",
          "Map iterasiyası",
          "Map metodları (getOrDefault, compute…)",
          "ConcurrentHashMap",
          "Map-ı sort etmək",
        ],
      },
      {
        id: "aj-5",
        title: "Generics",
        mins: 55,
        tags: ["theory", "practice"],
        subtopics: [
          "Generic class",
          "Generic method",
          "Bounded type parameters",
          "Wildcards (?, extends, super)",
          "Type erasure",
        ],
      },
      {
        id: "aj-6",
        title: "Lambda Expressions",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Lambda sintaksisi",
          "Functional interface",
          "Method references",
          "Constructor references",
          "Lambda vs Anonymous class",
        ],
      },
      {
        id: "aj-7",
        title: "Functional Interfaces",
        mins: 50,
        tags: ["theory", "practice"],
        subtopics: [
          "Predicate<T>",
          "Function<T,R>",
          "Consumer<T>",
          "Supplier<T>",
          "BiFunction, BiPredicate",
          "@FunctionalInterface",
        ],
      },
      {
        id: "aj-8",
        title: "Stream API",
        mins: 90,
        tags: ["theory", "practice"],
        subtopics: [
          "Stream yaratmaq",
          "filter, map, flatMap",
          "collect, reduce, count",
          "sorted, distinct, limit",
          "Parallel streams",
          "Collectors sinfi",
        ],
      },
      {
        id: "aj-9",
        title: "Optional Class",
        mins: 35,
        tags: ["practice"],
        subtopics: [
          "NullPointerException problemi",
          "Optional yaratmaq",
          "isPresent, get, orElse",
          "map, flatMap, filter",
          "Best practices",
        ],
      },
      {
        id: "aj-10",
        title: "Date & Time API (Java 8+)",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "LocalDate, LocalTime, LocalDateTime",
          "ZonedDateTime",
          "DateTimeFormatter",
          "Period & Duration",
          "Instant",
        ],
      },
      {
        id: "aj-11",
        title: "File I/O & NIO",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "java.io vs java.nio",
          "FileInputStream, FileOutputStream",
          "BufferedReader, BufferedWriter",
          "Path & Files API (NIO.2)",
          "WatchService – fayl dəyişikliklərini izlə",
          "Serialization & ObjectInputStream",
        ],
      },
      {
        id: "aj-12",
        title: "Reflection API",
        mins: 45,
        tags: ["theory", "practice"],
        subtopics: [
          "Class<?> ob'ekti almaq",
          "getDeclaredMethods, getDeclaredFields",
          "Annotation oxumaq (getAnnotation)",
          "Dynamic object yaratmaq (newInstance)",
          "Spring-də Reflection necə işlənir?",
          "Reflection performans overhead",
        ],
      },
      {
        id: "aj-13",
        title: "Custom Annotations",
        mins: 40,
        tags: ["theory", "practice"],
        subtopics: [
          "@interface sintaksisi",
          "Retention Policy (SOURCE, CLASS, RUNTIME)",
          "@Target (ElementType)",
          "Annotation Processor (APT)",
          "Spring AOP ilə custom annotation",
          "Nümunə: @LogExecutionTime",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 05 — Concurrency
     ───────────────────────────────────────── */
  {
    id: "concurrency",
    num: "05",
    icon: "🔄",
    title: "Multithreading & Concurrency",
    level: "Orta",
    color: "#ec4899",
    bg: "linear-gradient(135deg,#500724,#db2777)",
    hours: 20,
    desc: "Thread-lər, sinxronizasiya, Executor framework, CompletableFuture, Java Memory Model.",
    topics: [
      {
        id: "con-1",
        title: "Threads & Runnable",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Thread sinfi",
          "Runnable interface",
          "Thread lifecycle",
          "Thread priority",
          "daemon thread",
        ],
      },
      {
        id: "con-2",
        title: "Synchronization",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Race condition",
          "synchronized keyword",
          "volatile keyword",
          "Deadlock",
          "Livelock vs Starvation",
        ],
      },
      {
        id: "con-3",
        title: "Locks & Conditions",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "ReentrantLock",
          "ReadWriteLock",
          "Condition",
          "Lock vs synchronized",
          "StampedLock",
        ],
      },
      {
        id: "con-4",
        title: "Executor Framework",
        mins: 55,
        tags: ["theory", "practice"],
        subtopics: [
          "ExecutorService",
          "ThreadPoolExecutor",
          "ScheduledExecutorService",
          "Future & Callable",
          "Thread pool sizing",
        ],
      },
      {
        id: "con-5",
        title: "CompletableFuture",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "CompletableFuture yaratmaq",
          "thenApply, thenCompose, thenCombine",
          "exceptionally, handle",
          "allOf, anyOf",
          "Async metod zənciri",
        ],
      },
      {
        id: "con-6",
        title: "Concurrent Collections",
        mins: 40,
        tags: ["theory", "practice"],
        subtopics: [
          "ConcurrentHashMap",
          "CopyOnWriteArrayList",
          "BlockingQueue",
          "AtomicInteger, AtomicLong",
          "CountDownLatch, CyclicBarrier",
        ],
      },
      {
        id: "con-7",
        title: "Java Memory Model",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "Happens-before relation",
          "visibility problemi",
          "Memory visibility",
          "JMM və CPU caches",
          "Best practices",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 06 — JVM Internals & Performance
     ───────────────────────────────────────── */
  {
    id: "jvm-internals",
    num: "06",
    icon: "🔬",
    title: "JVM Internals & Performance",
    level: "İrəli",
    color: "#f43f5e",
    bg: "linear-gradient(135deg,#4c0519,#be123c)",
    hours: 16,
    desc: "Heap, Stack, Garbage Collection, memory leaks, JVM tuning, profiling alətləri.",
    topics: [
      {
        id: "jvm-1",
        title: "JVM Memory Architecture",
        mins: 60,
        tags: ["theory"],
        subtopics: [
          "Heap Memory – Young Gen (Eden, Survivor) & Old Gen",
          "Metaspace (Java 8+, PermGen-in əvəzi)",
          "Stack Memory – thread üçün ayrı frame stack",
          "Method Area",
          "Program Counter Register",
          "Heap vs Stack fərqlər",
        ],
      },
      {
        id: "jvm-2",
        title: "Garbage Collection – Anlayış",
        mins: 55,
        tags: ["theory"],
        subtopics: [
          "GC nədir? Avtomatik yaddaş idarəsi",
          "Object lifecycle (reachability)",
          "Minor GC vs Major GC vs Full GC",
          "GC Roots (stack variables, static fields)",
          "Mark-Sweep-Compact algoritması",
          "Generational GC hipotezi",
        ],
      },
      {
        id: "jvm-3",
        title: "GC Algoritmaları",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Serial GC",
          "Parallel GC (throughput collector)",
          "G1 GC – Garbage First (Java 9+ default)",
          "ZGC – ultra-low latency (Java 15+)",
          "Shenandoah GC",
          "GC seçim kriterləri",
        ],
      },
      {
        id: "jvm-4",
        title: "JVM Tuning & Flags",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "-Xms, -Xmx (initial/max heap)",
          "-XX:+UseG1GC, -XX:+UseZGC",
          "-XX:+PrintGCDetails, GC logging",
          "-XX:MetaspaceSize, -XX:MaxMetaspaceSize",
          "-Xss (thread stack size)",
          "Docker container-da JVM memory (-XX:+UseContainerSupport)",
        ],
      },
      {
        id: "jvm-5",
        title: "Memory Leaks & OutOfMemoryError",
        mins: 50,
        tags: ["theory", "practice"],
        subtopics: [
          "Memory leak nədir?",
          "OOM Error növləri: Java heap space, GC overhead limit, Metaspace",
          "Static collection leaks",
          "Unclosed resources & event listeners",
          "WeakReference, SoftReference, PhantomReference",
          "Heap dump analizi (Eclipse MAT)",
        ],
      },
      {
        id: "jvm-6",
        title: "Profiling & Monitoring Tools",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "JVisualVM – heap, threads, GC monitoring",
          "Java Flight Recorder (JFR)",
          "jstack – thread dump",
          "jmap – heap dump",
          "Async Profiler",
          "Spring Actuator JVM metrics",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 07 — Design Patterns
     ───────────────────────────────────────── */
  {
    id: "design-patterns",
    num: "07",
    icon: "🎨",
    title: "Design Patterns & SOLID",
    level: "Orta",
    color: "#a855f7",
    bg: "linear-gradient(135deg,#3b0764,#9333ea)",
    hours: 16,
    desc: "SOLID prinsipləri, GoF dizayn patternləri: Creational, Structural, Behavioral.",
    topics: [
      {
        id: "dp-1",
        title: "SOLID Principles",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "S – Single Responsibility",
          "O – Open/Closed",
          "L – Liskov Substitution",
          "I – Interface Segregation",
          "D – Dependency Inversion",
          "Real-world nümunələr",
        ],
      },
      {
        id: "dp-2",
        title: "Creational Patterns",
        mins: 70,
        tags: ["theory", "practice"],
        subtopics: [
          "Singleton",
          "Factory Method",
          "Abstract Factory",
          "Builder",
          "Prototype",
        ],
      },
      {
        id: "dp-3",
        title: "Structural Patterns",
        mins: 70,
        tags: ["theory", "practice"],
        subtopics: [
          "Adapter",
          "Decorator",
          "Proxy",
          "Facade",
          "Composite",
          "Bridge",
        ],
      },
      {
        id: "dp-4",
        title: "Behavioral Patterns",
        mins: 70,
        tags: ["theory", "practice"],
        subtopics: [
          "Observer",
          "Strategy",
          "Command",
          "Template Method",
          "Chain of Responsibility",
          "State",
          "Iterator",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 07 — Build Tools
     ───────────────────────────────────────── */
  {
    id: "build-tools",
    num: "08",
    icon: "🔧",
    title: "Build Tools",
    level: "Başlanğıc",
    color: "#6366f1",
    bg: "linear-gradient(135deg,#1e1b4b,#4338ca)",
    hours: 8,
    desc: "Maven və Gradle ilə Java proyektlərini qurmaq, asılılıqları idarə etmək.",
    topics: [
      {
        id: "bt-1",
        title: "Maven – POM & Lifecycle",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "pom.xml struktur",
          "groupId, artifactId, version",
          "Maven lifecycle (validate, compile, test, package…)",
          "Repositories",
          "Plugins",
        ],
      },
      {
        id: "bt-2",
        title: "Maven – Dependency Management",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "Dependency əlavə etmək",
          "Scope (compile, test, provided, runtime)",
          "Dependency tree",
          "Version conflicts",
          "BOM (Bill of Materials)",
        ],
      },
      {
        id: "bt-3",
        title: "Gradle – Əsaslar",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "build.gradle (Kotlin DSL vs Groovy DSL)",
          "Tasks",
          "Dependencies",
          "Plugins",
          "Maven vs Gradle müqayisə",
        ],
      },
      {
        id: "bt-4",
        title: "Multi-Module Projects",
        mins: 40,
        tags: ["practice"],
        subtopics: [
          "Maven multi-module",
          "Gradle multi-project",
          "Modul arası asılılıqlar",
          "Parent POM",
          "Practical nümunə",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 08 — Databases
     ───────────────────────────────────────── */
  {
    id: "databases",
    num: "09",
    icon: "🗄️",
    title: "Databases & SQL",
    level: "Başlanğıc",
    color: "#14b8a6",
    bg: "linear-gradient(135deg,#042f2e,#0d9488)",
    hours: 20,
    desc: "SQL, JDBC, transaction management, connection pooling, NoSQL-a giriş.",
    topics: [
      {
        id: "db-1",
        title: "SQL – DDL & DML Əsasları",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "CREATE, ALTER, DROP",
          "INSERT, UPDATE, DELETE",
          "SELECT, WHERE, ORDER BY",
          "Data types",
          "Constraints (PK, FK, UNIQUE, NOT NULL)",
        ],
      },
      {
        id: "db-2",
        title: "SQL – Joins & Subqueries",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "INNER JOIN",
          "LEFT/RIGHT/FULL OUTER JOIN",
          "CROSS JOIN",
          "Subqueries",
          "EXISTS, IN, ANY",
        ],
      },
      {
        id: "db-3",
        title: "SQL – Functions & Aggregations",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "GROUP BY, HAVING",
          "COUNT, SUM, AVG, MIN, MAX",
          "Window functions",
          "String/Date functions",
          "CASE expression",
        ],
      },
      {
        id: "db-4",
        title: "Indexes & Performance",
        mins: 50,
        tags: ["theory", "practice"],
        subtopics: [
          "Index nədir?",
          "B-Tree index",
          "Composite index",
          "EXPLAIN / EXPLAIN ANALYZE",
          "Index anti-patterns",
        ],
      },
      {
        id: "db-5",
        title: "Transactions & ACID",
        mins: 50,
        tags: ["theory"],
        subtopics: [
          "ACID properties",
          "BEGIN, COMMIT, ROLLBACK",
          "Isolation levels",
          "Dirty read, Phantom read",
          "Deadlock",
        ],
      },
      {
        id: "db-6",
        title: "JDBC",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "DriverManager",
          "Connection, Statement, PreparedStatement",
          "ResultSet",
          "Batch operations",
          "SQL Injection önləmə",
        ],
      },
      {
        id: "db-7",
        title: "Connection Pooling (HikariCP)",
        mins: 40,
        tags: ["practice"],
        subtopics: [
          "Connection pool nədir?",
          "HikariCP konfigurasiya",
          "Pool sizing",
          "Spring Boot ilə inteqrasiya",
          "Monitoring",
        ],
      },
      {
        id: "db-8",
        title: "NoSQL – Giriş",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "SQL vs NoSQL",
          "Document (MongoDB)",
          "Key-Value (Redis)",
          "Column (Cassandra)",
          "Graph (Neo4j)",
          "CAP theorem",
        ],
      },
      {
        id: "db-9",
        title: "Database Migration – Flyway & Liquibase",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "DB migration nədir? Niyə lazımdır?",
          "Flyway – versioned migrations (V1__, V2__...)",
          "Flyway: resources/db/migration/V1__init.sql",
          "Liquibase – changeset & changelog.xml",
          "Spring Boot ilə auto-migration (@EnableTransactionManagement)",
          "Flyway vs Liquibase müqayisə",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 10 — Spring Core
     ───────────────────────────────────────── */
  {
    id: "spring-core",
    num: "10",
    icon: "🌱",
    title: "Spring Framework Core",
    level: "Orta",
    color: "#22c55e",
    bg: "linear-gradient(135deg,#052e16,#16a34a)",
    hours: 18,
    desc: "IoC Container, Dependency Injection, Bean lifecycle, AOP, Spring Events.",
    topics: [
      {
        id: "sc-1",
        title: "Spring IoC Container",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "IoC nədir?",
          "ApplicationContext",
          "BeanFactory vs ApplicationContext",
          "XML vs Annotation vs Java Config",
          "Component scanning",
        ],
      },
      {
        id: "sc-2",
        title: "Dependency Injection",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Constructor injection",
          "Setter injection",
          "Field injection (@Autowired)",
          "Niyə constructor injection?",
          "@Qualifier, @Primary",
        ],
      },
      {
        id: "sc-3",
        title: "Spring Beans & Scopes",
        mins: 50,
        tags: ["theory", "practice"],
        subtopics: [
          "@Component, @Service, @Repository, @Controller",
          "Bean scopes (singleton, prototype, request, session)",
          "@Bean annotation",
          "Lazy initialization",
          "@Configuration sinfi",
        ],
      },
      {
        id: "sc-4",
        title: "Bean Lifecycle",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "BeanPostProcessor",
          "@PostConstruct, @PreDestroy",
          "InitializingBean, DisposableBean",
          "Lifecycle faza-ları",
          "Destroy bean order",
        ],
      },
      {
        id: "sc-5",
        title: "Spring AOP",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "AOP anlayışı (Aspect, Advice, Pointcut, Joinpoint)",
          "@Aspect, @Before, @After, @Around",
          "Logging & Security AOP",
          "Proxy mechanism",
          "Məhdudiyyətlər",
        ],
      },
      {
        id: "sc-6",
        title: "Spring Events",
        mins: 35,
        tags: ["practice"],
        subtopics: [
          "ApplicationEvent",
          "ApplicationEventPublisher",
          "@EventListener",
          "Async events",
          "Transaction-bound events",
        ],
      },
      {
        id: "sc-7",
        title: "Spring Expression Language (SpEL)",
        mins: 30,
        tags: ["practice"],
        subtopics: [
          "SpEL sintaksisi",
          "@Value ilə istifadə",
          "Şərtli ifadələr",
          "Collection manipulyasiyası",
          "Security ilə SpEL",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 10 — Spring Boot
     ───────────────────────────────────────── */
  {
    id: "spring-boot",
    num: "11",
    icon: "🚀",
    title: "Spring Boot",
    level: "Orta",
    color: "#f89820",
    bg: "linear-gradient(135deg,#431b00,#b45309)",
    hours: 16,
    desc: "Auto-configuration, starters, profiles, externalized config, DevTools, Actuator.",
    topics: [
      {
        id: "sb-1",
        title: "Spring Boot Giriş",
        mins: 45,
        tags: ["theory", "practice"],
        subtopics: [
          "Spring vs Spring Boot fərqi",
          "@SpringBootApplication",
          "Embedded server (Tomcat/Netty)",
          "start.spring.io",
          "İlk Spring Boot app",
        ],
      },
      {
        id: "sb-2",
        title: "Auto-Configuration",
        mins: 50,
        tags: ["theory"],
        subtopics: [
          "@EnableAutoConfiguration",
          "spring.factories / AutoConfiguration imports",
          "Conditional annotations",
          "@ConditionalOnClass",
          "Debug auto-config",
        ],
      },
      {
        id: "sb-3",
        title: "application.properties / .yml",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "Properties vs YAML",
          "Server port, datasource konfigurasiya",
          "@Value annotation",
          "@ConfigurationProperties",
          "Type-safe config",
        ],
      },
      {
        id: "sb-4",
        title: "Profiles",
        mins: 40,
        tags: ["practice"],
        subtopics: [
          "@Profile annotation",
          "application-dev.yml, application-prod.yml",
          "Active profile seçmək",
          "Profile-specific beans",
          "Multi-document YAML",
        ],
      },
      {
        id: "sb-5",
        title: "Spring Boot DevTools",
        mins: 25,
        tags: ["setup"],
        subtopics: [
          "Automatic restart",
          "LiveReload",
          "Remote debugging",
          "DevTools konfigurasiya",
          "Production-da DevTools",
        ],
      },
      {
        id: "sb-6",
        title: "Spring Boot Actuator",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "Actuator endpoints (/health, /info, /metrics)",
          "Custom health indicators",
          "Endpoint security",
          "Micrometer inteqrasiyası",
          "Custom metrics",
        ],
      },
      {
        id: "sb-7",
        title: "Exception Handling – Global",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "@ControllerAdvice, @RestControllerAdvice",
          "@ExceptionHandler",
          "ProblemDetail (RFC 7807)",
          "Custom error response",
          "Validation errors handling",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 11 — REST APIs
     ───────────────────────────────────────── */
  {
    id: "rest-apis",
    num: "12",
    icon: "🌐",
    title: "Building REST APIs",
    level: "Orta",
    color: "#60a5fa",
    bg: "linear-gradient(135deg,#172554,#2563eb)",
    hours: 22,
    desc: "RESTful prinsiplər, Spring MVC, request/response, versioning, pagination, Swagger.",
    topics: [
      {
        id: "ra-1",
        title: "REST Prinsipləri",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "REST nədir?",
          "6 REST constraint",
          "Stateless communication",
          "Resource-based design",
          "REST vs SOAP vs GraphQL",
        ],
      },
      {
        id: "ra-2",
        title: "HTTP Methods & Status Codes",
        mins: 45,
        tags: ["theory"],
        subtopics: [
          "GET, POST, PUT, PATCH, DELETE",
          "Idempotency",
          "2xx, 3xx, 4xx, 5xx status kodları",
          "Düzgün status kodu seçmək",
          "HEAD, OPTIONS",
        ],
      },
      {
        id: "ra-3",
        title: "@RestController & Routing",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "@RestController, @RequestMapping",
          "@GetMapping, @PostMapping…",
          "@PathVariable, @RequestParam",
          "@RequestBody, @ResponseBody",
          "ResponseEntity",
        ],
      },
      {
        id: "ra-4",
        title: "DTO Pattern & Validation",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "DTO nədir?",
          "MapStruct ilə mapping",
          "Bean Validation (@Valid, @NotNull…)",
          "Custom validators",
          "DTO vs Entity",
        ],
      },
      {
        id: "ra-5",
        title: "Pagination & Filtering",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "Pageable, PageRequest",
          "Sort",
          "Filter parameters",
          "Response envelop pattern",
          "Cursor-based pagination",
        ],
      },
      {
        id: "ra-6",
        title: "API Versioning",
        mins: 35,
        tags: ["theory", "practice"],
        subtopics: [
          "URL versioning (/api/v1/)",
          "Header versioning",
          "Media type versioning",
          "Hansı yanaşma daha yaxşı?",
          "Deprecation strategy",
        ],
      },
      {
        id: "ra-7",
        title: "Swagger / OpenAPI",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "springdoc-openapi",
          "@Operation, @ApiResponse, @Schema",
          "Swagger UI",
          "OpenAPI spec export",
          "Client code generation",
        ],
      },
      {
        id: "ra-8",
        title: "CORS & Content Negotiation",
        mins: 35,
        tags: ["practice"],
        subtopics: [
          "CORS nədir?",
          "@CrossOrigin",
          "Global CORS config",
          "Content-Type & Accept headers",
          "JSON & XML serializasiya",
        ],
      },
      {
        id: "ra-9",
        title: "RestTemplate & WebClient",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "RestTemplate (deprecated)",
          "WebClient (reactive)",
          "HTTP call etmək",
          "Error handling",
          "Timeout konfigurasiya",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 13 — Reactive Programming (Spring WebFlux)
     ───────────────────────────────────────── */
  {
    id: "reactive",
    num: "13",
    icon: "⚛️",
    title: "Reactive Programming (Spring WebFlux)",
    level: "İrəli",
    color: "#06b6d4",
    bg: "linear-gradient(135deg,#083344,#0e7490)",
    hours: 16,
    desc: "Project Reactor, Mono & Flux, Spring WebFlux, R2DBC, reactive streams.",
    topics: [
      {
        id: "rct-1",
        title: "Reactive Programming Anlayışı",
        mins: 45,
        tags: ["theory"],
        subtopics: [
          "Reactive Manifesto",
          "Imperative vs Reactive yanaşma",
          "Backpressure",
          "Reactive Streams Specification",
          "Nə zaman reactive?  (I/O-bound vs CPU-bound)",
        ],
      },
      {
        id: "rct-2",
        title: "Project Reactor – Mono & Flux",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "Mono<T> – 0 ya 1 element",
          "Flux<T> – 0..N elements",
          "Publisher, Subscriber, Subscription",
          "map, flatMap, filter, zip",
          "Error handling (onErrorReturn, onErrorResume)",
          "Testing: StepVerifier",
        ],
      },
      {
        id: "rct-3",
        title: "Spring WebFlux – Giriş",
        mins: 55,
        tags: ["theory", "practice"],
        subtopics: [
          "Spring MVC vs Spring WebFlux",
          "Netty (non-blocking server)",
          "@RestController reaktiv endpointlər",
          "Reactive vs thread-per-request model",
          "WebFlux-in üstünlükləri & çatışmazlıqları",
        ],
      },
      {
        id: "rct-4",
        title: "WebFlux – Functional Router",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "RouterFunction<ServerResponse>",
          "HandlerFunction",
          "RequestPredicates",
          "Annotation-based vs Functional web",
          "Nümunə: CRUD router",
        ],
      },
      {
        id: "rct-5",
        title: "R2DBC – Reactive Database",
        mins: 55,
        tags: ["theory", "practice"],
        subtopics: [
          "JDBC blocking problemi",
          "R2DBC nədir?",
          "R2DBC PostgreSQL / H2 driver",
          "ReactiveCrudRepository",
          "Spring Data R2DBC konfigurasiya",
        ],
      },
      {
        id: "rct-6",
        title: "WebClient (Reactive HTTP Client)",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "WebClient yaratmaq",
          "GET, POST, PUT requests",
          "Request/Response intercept",
          "Timeout & retry",
          "WebClient vs RestTemplate",
        ],
      },
      {
        id: "rct-7",
        title: "Reactive Security & Testing",
        mins: 40,
        tags: ["practice"],
        subtopics: [
          "Spring Security WebFlux ilə",
          "ReactiveSecurityContextHolder",
          "StepVerifier ilə unit test",
          "WebTestClient ilə integration test",
          "Reactive best practices",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 14 — JPA & Hibernate
     ───────────────────────────────────────── */
  {
    id: "jpa-hibernate",
    num: "14",
    icon: "🗃️",
    title: "Spring Data JPA & Hibernate",
    level: "Orta",
    color: "#fb923c",
    bg: "linear-gradient(135deg,#431407,#c2410c)",
    hours: 26,
    desc: "ORM anlayışı, entity mapping, relationships, JPQL, Spring Data repositories, N+1 problemi.",
    topics: [
      {
        id: "jpa-1",
        title: "ORM & JPA Anlayışı",
        mins: 45,
        tags: ["theory"],
        subtopics: [
          "ORM nədir?",
          "JPA specification",
          "Hibernate JPA provider kimi",
          "Persistence context",
          "Entity state (transient, managed, detached, removed)",
        ],
      },
      {
        id: "jpa-2",
        title: "Entity Mapping",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "@Entity, @Table",
          "@Id, @GeneratedValue",
          "@Column, @Transient",
          "Embeddable & @Embedded",
          "Inheritance strategies",
        ],
      },
      {
        id: "jpa-3",
        title: "Relationships – OneToMany, ManyToOne",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "@OneToMany, @ManyToOne",
          "Bidirectional vs Unidirectional",
          "mappedBy",
          "Cascade types",
          "Orphan removal",
        ],
      },
      {
        id: "jpa-4",
        title: "Relationships – ManyToMany, OneToOne",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "@ManyToMany, @JoinTable",
          "@OneToOne",
          "Bidirectional problems",
          "DTO projection patterns",
          "Association tables",
        ],
      },
      {
        id: "jpa-5",
        title: "Fetch Types & N+1 Problem",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "LAZY vs EAGER loading",
          "N+1 problemi",
          "JOIN FETCH",
          "@EntityGraph",
          "Batch fetching",
          "Hibernate statistics",
        ],
      },
      {
        id: "jpa-6",
        title: "JPQL & Named Queries",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "JPQL sintaksisi",
          "SELECT, WHERE, JOIN",
          "@NamedQuery, @NamedNativeQuery",
          "Native SQL queries",
          "Bulk update/delete",
        ],
      },
      {
        id: "jpa-7",
        title: "Spring Data Repositories",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "JpaRepository, CrudRepository",
          "Derived query methods",
          "@Query annotation",
          "Modifying queries",
          "Custom repository implementation",
        ],
      },
      {
        id: "jpa-8",
        title: "Pagination, Sorting & Specifications",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "Pageable ilə pagination",
          "JpaSpecificationExecutor",
          "Specification API",
          "QueryDSL giriş",
          "Dynamic queries",
        ],
      },
      {
        id: "jpa-9",
        title: "Hibernate Caching",
        mins: 45,
        tags: ["theory", "practice"],
        subtopics: [
          "First-level cache",
          "Second-level cache",
          "Query cache",
          "Ehcache / Redis ilə",
          "Cache invalidation",
        ],
      },
      {
        id: "jpa-10",
        title: "Optimistic vs Pessimistic Lock",
        mins: 40,
        tags: ["theory", "practice"],
        subtopics: [
          "Optimistic locking (@Version)",
          "Pessimistic locking",
          "Lock modes",
          "Conflict resolution",
          "Distributed locking",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 13 — Spring Security
     ───────────────────────────────────────── */
  {
    id: "spring-security",
    num: "15",
    icon: "🔐",
    title: "Spring Security",
    level: "İrəli",
    color: "#ef4444",
    bg: "linear-gradient(135deg,#450a0a,#dc2626)",
    hours: 20,
    desc: "Authentication, Authorization, JWT, OAuth 2.0, CSRF, CORS, method security.",
    topics: [
      {
        id: "ss-1",
        title: "Security Fundamentals",
        mins: 45,
        tags: ["theory"],
        subtopics: [
          "Authentication vs Authorization",
          "Autentifikasiya növləri",
          "Credentials storage best practices",
          "Password hashing (BCrypt)",
          "Security threat model",
        ],
      },
      {
        id: "ss-2",
        title: "Spring Security Architecture",
        mins: 50,
        tags: ["theory"],
        subtopics: [
          "SecurityFilterChain",
          "AuthenticationManager",
          "UserDetailsService",
          "SecurityContext",
          "Filter order",
        ],
      },
      {
        id: "ss-3",
        title: "Form Login & In-Memory Auth",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "SecurityFilterChain konfigurasiya",
          "UserDetailsService implementasiya",
          "PasswordEncoder",
          "Role-based access",
          "Remember-me",
        ],
      },
      {
        id: "ss-4",
        title: "JWT Authentication",
        mins: 75,
        tags: ["practice"],
        subtopics: [
          "JWT struktur (Header.Payload.Signature)",
          "JWT yaratmaq (jjwt library)",
          "JwtAuthenticationFilter",
          "Refresh tokens",
          "Token blacklisting",
        ],
      },
      {
        id: "ss-5",
        title: "OAuth 2.0 & OpenID Connect",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "OAuth 2.0 flows (Authorization Code, Client Credentials)",
          "Spring Authorization Server",
          "Resource Server konfigurasiya",
          "Google/GitHub Login",
          "OIDC tokens",
        ],
      },
      {
        id: "ss-6",
        title: "CSRF & CORS",
        mins: 40,
        tags: ["theory", "practice"],
        subtopics: [
          "CSRF nədir?",
          "CSRF token",
          "Spring CSRF konfigurasiya",
          "CORS policy",
          "Preflight requests",
        ],
      },
      {
        id: "ss-7",
        title: "Method Security",
        mins: 40,
        tags: ["practice"],
        subtopics: [
          "@PreAuthorize, @PostAuthorize",
          "@Secured",
          "@RolesAllowed",
          "SpEL ilə dinamik permissions",
          "ACL (Access Control List)",
        ],
      },
      {
        id: "ss-8",
        title: "Keycloak & IAM Integration",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "Keycloak nədir?",
          "Realm & Client konfigurasiya",
          "Spring Boot ilə Keycloak",
          "Token validation",
          "Role sync",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 14 — Testing
     ───────────────────────────────────────── */
  {
    id: "testing",
    num: "16",
    icon: "✅",
    title: "Testing",
    level: "Orta",
    color: "#34d399",
    bg: "linear-gradient(135deg,#022c22,#059669)",
    hours: 18,
    desc: "JUnit 5, Mockito, MockMvc, integration testing, Testcontainers, TDD prinsipi.",
    topics: [
      {
        id: "tst-1",
        title: "Testing Prinsipləri & Pyramid",
        mins: 35,
        tags: ["theory"],
        subtopics: [
          "Test pyramid",
          "Unit, Integration, E2E testlər",
          "Test coverage",
          "Testing anti-patterns",
          "Test yazmanın faydaları",
        ],
      },
      {
        id: "tst-2",
        title: "JUnit 5 – Əsaslar",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "@Test, @BeforeEach, @AfterEach",
          "@BeforeAll, @AfterAll",
          "Assertions (assertEquals, assertThrows…)",
          "@DisplayName",
          "@Nested test classes",
        ],
      },
      {
        id: "tst-3",
        title: "JUnit 5 – Parametrized Tests",
        mins: 40,
        tags: ["practice"],
        subtopics: [
          "@ParameterizedTest",
          "@ValueSource, @CsvSource",
          "@MethodSource",
          "@EnumSource",
          "Test data providers",
        ],
      },
      {
        id: "tst-4",
        title: "Mockito",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "@Mock, @InjectMocks",
          "when().thenReturn()",
          "verify()",
          "ArgumentCaptor",
          "Spy objects",
          "MockitoExtension",
        ],
      },
      {
        id: "tst-5",
        title: "Spring MVC Test (MockMvc)",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "@WebMvcTest",
          "MockMvc setup",
          "perform GET/POST",
          "jsonPath assertions",
          "Security test",
        ],
      },
      {
        id: "tst-6",
        title: "Integration Testing",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "@SpringBootTest",
          "TestRestTemplate",
          "WebTestClient",
          "@AutoConfigureTestDatabase",
          "Profile: test",
        ],
      },
      {
        id: "tst-7",
        title: "Testcontainers",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "Testcontainers nədir?",
          "PostgreSQL container",
          "Kafka container",
          "Redis container",
          "@Testcontainers annotation",
        ],
      },
      {
        id: "tst-8",
        title: "Test-Driven Development (TDD)",
        mins: 45,
        tags: ["theory", "practice"],
        subtopics: [
          "Red-Green-Refactor cycle",
          "TDD faydaları",
          "Practical TDD example",
          "TDD vs BDD",
          "TDD limitləri",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 15 — Caching
     ───────────────────────────────────────── */
  {
    id: "caching",
    num: "17",
    icon: "💾",
    title: "Caching",
    level: "Orta",
    color: "#38bdf8",
    bg: "linear-gradient(135deg,#082f49,#0369a1)",
    hours: 10,
    desc: "Caching konseptləri, Spring Cache abstraction, Caffeine, Redis, cache strategiyaları.",
    topics: [
      {
        id: "cch-1",
        title: "Caching Konseptləri",
        mins: 35,
        tags: ["theory"],
        subtopics: [
          "Cache nədir?",
          "Cache hit vs miss",
          "Eviction policies (LRU, LFU)",
          "TTL",
          "Distributed vs Local cache",
        ],
      },
      {
        id: "cch-2",
        title: "Spring Cache Abstraction",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "@EnableCaching",
          "@Cacheable, @CacheEvict, @CachePut",
          "@Caching",
          "CacheManager",
          "Conditional caching",
        ],
      },
      {
        id: "cch-3",
        title: "Caffeine Cache",
        mins: 35,
        tags: ["practice"],
        subtopics: [
          "Caffeine nədir?",
          "Maksimum size konfigurasiya",
          "Expiration policy",
          "Statistics",
          "Spring ilə inteqrasiya",
        ],
      },
      {
        id: "cch-4",
        title: "Redis – Giriş",
        mins: 45,
        tags: ["theory", "practice"],
        subtopics: [
          "Redis nədir?",
          "Data structures (String, Hash, List, Set, Sorted Set)",
          "Redis CLI",
          "Docker ilə Redis",
          "TTL management",
        ],
      },
      {
        id: "cch-5",
        title: "Spring Data Redis",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "RedisTemplate",
          "StringRedisTemplate",
          "RedisRepository",
          "@RedisHash",
          "Spring Cache + Redis",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 16 — Messaging
     ───────────────────────────────────────── */
  {
    id: "messaging",
    num: "18",
    icon: "📨",
    title: "Message Queues & Messaging",
    level: "İrəli",
    color: "#fb7185",
    bg: "linear-gradient(135deg,#4c0519,#e11d48)",
    hours: 14,
    desc: "Messaging konseptləri, RabbitMQ, Apache Kafka, Event-Driven Architecture.",
    topics: [
      {
        id: "msg-1",
        title: "Messaging Konseptləri",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "Sync vs Async communication",
          "Message broker",
          "Queue vs Topic",
          "Publish-Subscribe pattern",
          "Message ordering & durability",
        ],
      },
      {
        id: "msg-2",
        title: "RabbitMQ – Əsaslar",
        mins: 50,
        tags: ["theory", "practice"],
        subtopics: [
          "AMQP protokolu",
          "Exchange, Queue, Binding",
          "Exchange types (Direct, Topic, Fanout, Headers)",
          "Message acknowledgment",
          "Dead Letter Queue",
        ],
      },
      {
        id: "msg-3",
        title: "Spring AMQP (RabbitMQ)",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "RabbitTemplate",
          "@RabbitListener",
          "MessageConverter (JSON)",
          "Error handling",
          "Retry mechanism",
        ],
      },
      {
        id: "msg-4",
        title: "Apache Kafka – Əsaslar",
        mins: 55,
        tags: ["theory", "practice"],
        subtopics: [
          "Kafka arxitekturası",
          "Topics, Partitions, Offsets",
          "Producer & Consumer",
          "Consumer Groups",
          "Log compaction",
        ],
      },
      {
        id: "msg-5",
        title: "Spring Kafka",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "KafkaTemplate",
          "@KafkaListener",
          "Consumer Group Config",
          "Error handling (SeekToCurrentErrorHandler)",
          "Transactions in Kafka",
        ],
      },
      {
        id: "msg-6",
        title: "Event-Driven Architecture",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "Event-Driven vs Request-Driven",
          "Choreography vs Orchestration",
          "Outbox pattern",
          "Saga pattern",
          "Eventual consistency",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 17 — Docker
     ───────────────────────────────────────── */
  {
    id: "docker",
    num: "19",
    icon: "🐳",
    title: "Docker & Containers",
    level: "Orta",
    color: "#2563eb",
    bg: "linear-gradient(135deg,#172554,#1d4ed8)",
    hours: 14,
    desc: "Docker anlayışı, Dockerfile, Docker Compose, Spring Boot app-larını containerize etmək.",
    topics: [
      {
        id: "dkr-1",
        title: "Docker Giriş",
        mins: 45,
        tags: ["theory", "practice"],
        subtopics: [
          "Container vs VM",
          "Docker daemon & CLI",
          "Image vs Container",
          "Docker Hub",
          "Əsas komandalar (pull, run, ps, stop, rm)",
        ],
      },
      {
        id: "dkr-2",
        title: "Dockerfile",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "FROM, RUN, COPY, WORKDIR, CMD",
          "Build context",
          "Multi-stage build",
          ".dockerignore",
          "Image layer optimization",
        ],
      },
      {
        id: "dkr-3",
        title: "Docker Compose",
        mins: 60,
        tags: ["practice"],
        subtopics: [
          "docker-compose.yml struktur",
          "Services, networks, volumes",
          "Environment variables",
          "Depends_on & health checks",
          "Spring Boot + PostgreSQL + Redis",
        ],
      },
      {
        id: "dkr-4",
        title: "Docker Networking & Volumes",
        mins: 40,
        tags: ["theory", "practice"],
        subtopics: [
          "Bridge, host, none networks",
          "Container-to-container communication",
          "Bind mounts vs Volumes",
          "Volume backup",
          "Named volumes",
        ],
      },
      {
        id: "dkr-5",
        title: "Spring Boot Dockerization",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "Spring Boot uber JAR",
          "Jib Maven/Gradle plugin",
          "Layered JAR",
          "BuildPacks (Cloud Native Buildpacks)",
          "Production-ready image",
        ],
      },
      {
        id: "dkr-6",
        title: "Kubernetes Giriş",
        mins: 50,
        tags: ["theory"],
        subtopics: [
          "Kubernetes nədir?",
          "Pod, Deployment, Service, ConfigMap",
          "kubectl əsas komandaları",
          "Minikube ilə local cluster",
          "Kubernetes vs Docker Compose",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 18 — Microservices
     ───────────────────────────────────────── */
  {
    id: "microservices",
    num: "20",
    icon: "☸️",
    title: "Microservices Architecture",
    level: "İrəli",
    color: "#818cf8",
    bg: "linear-gradient(135deg,#1e1b4b,#4f46e5)",
    hours: 24,
    desc: "Microservices pattern-ləri, Spring Cloud, Service Discovery, API Gateway, Circuit Breaker.",
    topics: [
      {
        id: "ms-1",
        title: "Monolith vs Microservices",
        mins: 45,
        tags: ["theory"],
        subtopics: [
          "Monolith yanaşması",
          "Microservices yanaşması",
          "Trade-offs",
          "Nə zaman microservices?",
          "Domain-Driven Design giriş",
        ],
      },
      {
        id: "ms-2",
        title: "Spring Cloud Overview",
        mins: 45,
        tags: ["theory"],
        subtopics: [
          "Spring Cloud nədir?",
          "Spring Cloud Netflix",
          "Spring Cloud LoadBalancer",
          "Spring Cloud Gateway",
          "Spring Cloud Config",
        ],
      },
      {
        id: "ms-3",
        title: "Service Discovery (Eureka)",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "Service discovery problemi",
          "Eureka Server setup",
          "Eureka Client registration",
          "Self-preservation mode",
          "DNS-based discovery",
        ],
      },
      {
        id: "ms-4",
        title: "API Gateway",
        mins: 55,
        tags: ["theory", "practice"],
        subtopics: [
          "API Gateway pattern",
          "Spring Cloud Gateway setup",
          "Route konfigurasiya",
          "Filters (pre/post)",
          "Rate limiting",
          "Authentication filter",
        ],
      },
      {
        id: "ms-5",
        title: "Circuit Breaker (Resilience4j)",
        mins: 55,
        tags: ["theory", "practice"],
        subtopics: [
          "Circuit Breaker pattern",
          "Resilience4j setup",
          "@CircuitBreaker",
          "Fallback method",
          "Retry, Bulkhead, RateLimiter",
          "Monitoring circuit state",
        ],
      },
      {
        id: "ms-6",
        title: "Distributed Tracing",
        mins: 45,
        tags: ["theory", "practice"],
        subtopics: [
          "Tracing problemi",
          "Trace ID & Span ID",
          "Micrometer Tracing",
          "Zipkin inteqrasiya",
          "Baggage propagation",
        ],
      },
      {
        id: "ms-7",
        title: "Config Server",
        mins: 40,
        tags: ["practice"],
        subtopics: [
          "Centralized config",
          "Spring Cloud Config Server",
          "Git backend",
          "Config refresh",
          "Encryption",
        ],
      },
      {
        id: "ms-8",
        title: "Inter-service Communication",
        mins: 50,
        tags: ["theory", "practice"],
        subtopics: [
          "Synchronous (REST, gRPC)",
          "Asynchronous (Kafka, RabbitMQ)",
          "OpenFeign client",
          "Service mesh (Istio giriş)",
          "Communication patterns",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 19 — Monitoring & Logging
     ───────────────────────────────────────── */
  {
    id: "monitoring",
    num: "21",
    icon: "📊",
    title: "Monitoring & Logging",
    level: "İrəli",
    color: "#c084fc",
    bg: "linear-gradient(135deg,#2e1065,#7c3aed)",
    hours: 14,
    desc: "SLF4J, Logback, Spring Actuator, Prometheus, Grafana, ELK Stack.",
    topics: [
      {
        id: "mon-1",
        title: "Logging – SLF4J & Logback",
        mins: 50,
        tags: ["practice"],
        subtopics: [
          "SLF4J nədir?",
          "Logger instance",
          "Log levels (TRACE, DEBUG, INFO, WARN, ERROR)",
          "logback.xml konfigurasiya",
          "Rolling file appenders",
          "Structured logging",
        ],
      },
      {
        id: "mon-2",
        title: "Spring Boot Actuator",
        mins: 40,
        tags: ["practice"],
        subtopics: [
          "/health, /metrics, /info, /env endpoints",
          "Custom health indicator",
          "Custom metrics",
          "Endpoint exposure konfigurasiya",
          "Security",
        ],
      },
      {
        id: "mon-3",
        title: "Micrometer & Metrics",
        mins: 40,
        tags: ["theory", "practice"],
        subtopics: [
          "Micrometer nədir?",
          "Counter, Gauge, Timer, Summary",
          "@Timed annotation",
          "Custom metrics",
          "Tags (labels)",
        ],
      },
      {
        id: "mon-4",
        title: "Prometheus",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "Prometheus setup",
          "PromQL əsasları",
          "Scrape config",
          "Alerting rules",
          "Spring Boot + Prometheus",
        ],
      },
      {
        id: "mon-5",
        title: "Grafana",
        mins: 45,
        tags: ["practice"],
        subtopics: [
          "Grafana setup",
          "Dashboard yaratmaq",
          "Panel types",
          "Alerting",
          "JVM metrics dashboard",
        ],
      },
      {
        id: "mon-6",
        title: "ELK Stack Giriş",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "Elasticsearch",
          "Logstash",
          "Kibana",
          "Filebeat",
          "Logback ilə ELK inteqrasiya",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 20 — Cloud & DevOps
     ───────────────────────────────────────── */
  {
    id: "cloud-devops",
    num: "22",
    icon: "☁️",
    title: "Cloud & DevOps",
    level: "İrəli",
    color: "#67e8f9",
    bg: "linear-gradient(135deg,#083344,#0891b2)",
    hours: 16,
    desc: "CI/CD pipeline, GitHub Actions, AWS əsasları, deployment strategiyaları.",
    topics: [
      {
        id: "cd-1",
        title: "CI/CD Konseptləri",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "Continuous Integration",
          "Continuous Delivery vs Deployment",
          "Pipeline stages",
          "Artifact management",
          "Rollback strategies",
        ],
      },
      {
        id: "cd-2",
        title: "GitHub Actions",
        mins: 55,
        tags: ["practice"],
        subtopics: [
          "workflow.yml struktur",
          "Triggers (push, pull_request)",
          "Jobs & Steps",
          "Actions marketplace",
          "Build + Test + Deploy pipeline",
        ],
      },
      {
        id: "cd-3",
        title: "AWS – Java Developer üçün",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "EC2 – virtual machines",
          "RDS – managed database",
          "S3 – object storage",
          "ECS/Fargate – container hosting",
          "IAM – permissions",
        ],
      },
      {
        id: "cd-4",
        title: "Deployment Strategiyaları",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "Blue-Green deployment",
          "Canary deployment",
          "Rolling deployment",
          "Feature flags",
          "Zero-downtime deployment",
        ],
      },
      {
        id: "cd-5",
        title: "Infrastructure as Code",
        mins: 40,
        tags: ["theory"],
        subtopics: [
          "IaC nədir?",
          "Terraform giriş",
          "Ansible giriş",
          "CloudFormation",
          "IaC best practices",
        ],
      },
      {
        id: "cd-6",
        title: "Container Registry & Orchestration",
        mins: 40,
        tags: ["practice"],
        subtopics: [
          "Docker Hub",
          "AWS ECR",
          "ECS Task Definition",
          "EKS (Kubernetes on AWS)",
          "Helm charts giriş",
        ],
      },
    ],
  },

  /* ─────────────────────────────────────────
     SECTION 21 — Interview Prep
     ───────────────────────────────────────── */
  {
    id: "interview-prep",
    num: "23",
    icon: "🎯",
    title: "Interview Preparation",
    level: "Ekspert",
    color: "#fbbf24",
    bg: "linear-gradient(135deg,#451a03,#d97706)",
    hours: 16,
    desc: "Java, Spring, DB, sistem dizayn sualları və kodlama tapşırıqlarına hazırlıq.",
    topics: [
      {
        id: "ip-1",
        title: "Core Java Sualları",
        mins: 90,
        tags: ["theory", "practice"],
        subtopics: [
          "OOP sualları",
          "JVM & Memory model",
          "Collections sualları",
          "Multithreading sualları",
          "Java 8+ sualları",
          "Top 50 Java interview sualı",
        ],
      },
      {
        id: "ip-2",
        title: "Spring & Spring Boot Sualları",
        mins: 80,
        tags: ["theory"],
        subtopics: [
          "Spring IoC/DI sualları",
          "Spring Boot auto-config",
          "Spring Security sualları",
          "JPA/Hibernate sualları",
          "REST API design sualları",
        ],
      },
      {
        id: "ip-3",
        title: "Database & SQL Sualları",
        mins: 60,
        tags: ["theory", "practice"],
        subtopics: [
          "SQL optimization",
          "Index sualları",
          "Transaction isolation",
          "ORM vs raw SQL",
          "NoSQL ne zaman?",
        ],
      },
      {
        id: "ip-4",
        title: "System Design – Əsaslar",
        mins: 90,
        tags: ["theory"],
        subtopics: [
          "Scalability (horizontal vs vertical)",
          "Load balancing",
          "Caching strategies",
          "Database sharding & replication",
          "CAP theorem",
          "URL shortener dizaynı",
        ],
      },
      {
        id: "ip-5",
        title: "Coding Challenges",
        mins: 120,
        tags: ["practice"],
        subtopics: [
          "Arrays & Strings",
          "LinkedList & Tree problems",
          "HashMap & Set patterns",
          "Dynamic Programming giriş",
          "LeetCode Easy/Medium",
          "Big O analysis",
        ],
      },
      {
        id: "ip-6",
        title: "Soft Skills & Career",
        mins: 45,
        tags: ["theory"],
        subtopics: [
          "STAR metodu ilə davranış sualları",
          "Maaş müzakirəsi",
          "Portfolio & GitHub",
          "LinkedIn optimization",
          "Junior → Mid → Senior yolu",
        ],
      },
    ],
  },
];

/* ─── Helpers ─── */

function getAllTopics() {
  return CURRICULUM.flatMap((s) =>
    s.topics.map((t) => ({
      ...t,
      sectionId: s.id,
      sectionTitle: s.title,
      sectionIcon: s.icon,
    })),
  );
}

function getSectionById(id) {
  return CURRICULUM.find((s) => s.id === id) || null;
}

function getTopicById(topicId) {
  for (const s of CURRICULUM) {
    const t = s.topics.find((t) => t.id === topicId);
    if (t) return { ...t, section: s };
  }
  return null;
}

function getNeighborTopics(topicId) {
  const all = getAllTopics();
  const idx = all.findIndex((t) => t.id === topicId);
  return {
    prev: idx > 0 ? all[idx - 1] : null,
    next: idx < all.length - 1 ? all[idx + 1] : null,
  };
}

function getTotalTopicsCount() {
  return CURRICULUM.reduce((a, s) => a + s.topics.length, 0);
}
